### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by iguanajazz**
## Changes

Adds my name to the Spanish (ES_UN) language.

As part of initial team as mentioned in https://github.com/Qiskit/platypus/issues/1014

### CODE REVIEW

**Comment by iguanajazz** [comment]
I've joined GitLocalize!

**Comment by techtolentino** [comment]
@0sophy1 @veenaiyuri - this looks good to me... would you like to review anything here?

**Comment by 0sophy1** [comment]
gitlocalize onboarded! this PR is ready to merge!

**Review by techtolentino — APPROVED** [review]
Thanks for this @iguanajazz and @0sophy1 👏

**Comment by iguanajazz** [comment]
@0sophy1 Hi, I don't see the platypus project in my list of projects in GitLocalize, do I have to do something else?

**Comment by 0sophy1** [comment]
added!

**Pull request merged**
