### PR TITLE
feat(1xp-banner): add banner to `/signin`, `/account`, and `/error` pages

### LINKED ISSUE #2189: Add 1XP banner to "Account" and "Sign in" pages
### Feature description

We need to add the newest 1XP banner added in https://github.com/Qiskit/platypus/issues/2158 to the "Account" pages and the "Sign in" page.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by techtolentino**
## Changes

Closes #2189 

## Implementation details

- added `q-one-xp-banner` to `signin.pug`, `userAccount.pug`, and `error.pug` templates
- pulled `$one-xp-banner-height-*` variables into the `settings.scss` since it's used in multiple scss files
- updated `.sign-in` styles to make banner work
  - note: I had to add a `1px` to the `top` and `max-height` calculations so the bottom-border of the banner would show

## Screenshots
**Sign in and Account pages**

https://github.com/Qiskit/platypus/assets/6276074/bf50142b-7dfd-4f44-ba95-9888d2f209ce

**Error page**
Screenshot 2023-09-06 at 2 50 03 PM (2)

preview of sign in page: https://platypus-pr-2195.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/signin
preview of error page: https://platypus-pr-2195.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/test

### CODE REVIEW

**Review by vabarbosa — DISMISSED** [review]
thank you! this looks good @techtolentino 
 i am approving so we can merge this but
while we are here you may want to confirm if banner should be included it on the following and if so maybe open/create new issue/PR

### EULA page
image

### 404 page
image

 ### syllabus pages

image

image

**Comment by techtolentino** [comment]
@vabarbosa - I thought about these pages but didn't fully know if they should be _everywhere_

maybe they should?

@y4izus?

**Comment by vabarbosa** [comment]
> @vabarbosa - I thought about these pages but didn't fully know if they should be _everywhere_
> 
> 
> 

at minimum i would say the 404 page should have banner. i'm ok leaving the other pages as is though.

**Comment by techtolentino** [comment]
> at minimum i would say the 404 page should have the banner. i'm ok with leaving the other pages as is though.

@vabarbosa - good idea, updated here https://github.com/Qiskit/platypus/pull/2195/commits/1e9e6ab543b29f4591d5dfce5fbba432027a3e93

**Review by vabarbosa — APPROVED** [review]
thank you @techtolentino!!!
looks good!

**Comment by y4izus** [comment]
I think is enough with that pages, so I'm gonna merge

**Pull request merged**
