### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by derwind**
## Changes

- Added my name as a localization contributor for the Japanese language.

## Implementation details

- I would like to participate in the Qiskit textbook translation project.

### CODE REVIEW

**Comment by vabarbosa** [comment]
@derwind Thanks for interest in the Qiskit Textbook localization project. Please let us know in the comments when you have successfully joined [GitLocalize](https://gitlocalize.com/) so you can be added you to the project.

CC @veenaiyuri

**Comment by derwind** [comment]
@vabarbosa @veenaiyuri 
Thank for your reply. I have already joined GitLocalize.

**Comment by derwind** [comment]
@vabarbosa @veenaiyuri
It appears that there was a conflict in the LOCALIZATION_CONTRIBUTORS file and I have resolved it. And I'm happy if you could let me know if there are any omissions in the procedure.

**Comment by veenaiyuri** [comment]
@derwind Thanks for the reminder and for joining the Qiskit Textbook localization project. Resolved conflict.

**Review by veenaiyuri — APPROVED** [review]
Reviewed his request and confirmed that he successfully joined GitLocalized.

**Pull request merged**
