### PR TITLE
Add Lab04 and re-order remaining labs

### PR DESCRIPTION
**Pull request by gunchamalik**
Lab 04 caters to Bell Circuit and GHZ Circuit. Previous Lab04 to Lab08 have been renamed to Lab05 to Lab09 along with their images.

### CODE REVIEW

**Comment by frankharkins** [comment]
Hi, thanks again for updating. My only comment this time is I don't think you should display all possible states for all possible inputs. In cells 3 & 9, I think one set of plot_bloch_multivectors are enough since they all look the same regardless of output. For the plot_state_qspheres in cell 11, maybe just choose 2 or 3 interesting states to show and the reader can choose to show more if they need.

**Comment by gunchamalik** [comment]
@frankharkins Updated cells 3, 9 and 11.

**Comment by frankharkins** [comment]
Thank you!

**Comment by eddybrando** [comment]
@frankharkins, is the current state ready for merging in your opinion?

**Comment by frankharkins** [comment]
@eddybrando yes I think it's fine :)

**Review by vabarbosa — CHANGES_REQUESTED** [review]
@gunchamalik my apologies for getting to this so late. a couple changes still needed:

- fix the lab `id`'s and `url`'s in the [`toc.yaml`](https://github.com/gunchamalik/platypus/blob/main/notebooks/toc.yaml#L164-L192) to correctly match the new updates
- fix the lab `label`'s, `url`'s, and `action`'s in the [`megaMenuLinks.ts`](https://github.com/gunchamalik/platypus/blob/main/frontend/vue/components/constants/megaMenuLinks.ts#L469-L537) to correctly match the new updates

**Comment by gunchamalik** [comment]
@vabarbosa I have made the updates to toc.yaml and megaMenuLinks.ts

**Comment by vabarbosa** [comment]
i am merging this into a [feature branch](https://github.com/Qiskit/platypus/tree/feature/lab04-update) so we can get a preview for a final review

**Pull request merged**
