### PR TITLE
Added heagan01 to list of Indonesia contributors

### PR DESCRIPTION
**Pull request by heagan01**

### CODE REVIEW

**Comment by heagan01** [comment]
I've already signed the CLA, and have already registered to gitlocalize.

**Comment by vabarbosa** [comment]
@Qiskit/qiskit-translation are we all set here?

**Comment by vabarbosa** [comment]
@Qiskit/qiskit-translation

**Review by 0sophy1 — APPROVED** [review]
Thank you so much @heagan01 and sorry for this huge delay. Hope you enjoy localization and von voyage!

**Comment by heagan01** [comment]
thank you @0sophy1

**Pull request merged**
