### PR TITLE
Update HowtoTranslate_QiskitTextbook_ja.pdf

### PR DESCRIPTION
**Pull request by kifumi**
## Changes
How to translate the qiskit textbook with GitLocalize.  Updated the last page for proofreading including below notes:
1) Use "+" in order to add the comment on each notebooks.
2) Add "Proofreading done. Please send PR." in the conversation of review request after proofreading.

### CODE REVIEW

**Comment by techtolentino** [comment]
@kifumi - just a FYI:

Our team will soon have a pretty big update to the `qiskit.org/textbook-beta` page. That URL will be deprecated and will become `qiskit.org/learn`

To avoid you having to redo this PDF, maybe we should wait until those merges are done, and you can update this document to use `/learn` instead of `/textbook-beta`.



What do you think?

**Comment by techtolentino** [comment]
@kifumi - just a FYI:

Our team will soon have a pretty big update to the `qiskit.org/textbook-beta` page. That URL will be deprecated and will become `qiskit.org/learn`

To avoid you having to redo this PDF, maybe we should wait until those merges are done, and you can update this document to use `/learn` instead of `/textbook-beta`.



What do you think?

**Review by techtolentino — CHANGES_REQUESTED** [review]
@kifumi 

We've merged the https://qiskit.org/learn updates.
If you have any references to `/textbook-beta` in your PDF, is it possible to update it to `https://qiskit.org/learn`?

Screen Shot 2022-06-09 at 12 00 07 PM

**Comment by kifumi** [comment]
@techtolentino Sorry for my late response. I updated the URL.  Thank you the comment.

**Review by techtolentino — APPROVED** [review]
Thank you for updating this, @kifumi 

Looks good to me 🚀

**Pull request merged**
