### PR TITLE
Lab1 grading exercises

### LINKED ISSUE #360: Grader: Update Lab 1 Quantum Circuits to integrate grading component
Related 
- https://github.com/Qiskit/platypus/issues/253
- https://github.com/Qiskit/platypus/issues/359

### PR DESCRIPTION
**Pull request by vabarbosa**
> _this PR is a replacement of #797_
> 

## Changes

Fixes #360 

this PR updates Lab 1 of the textbook and modifies its exercises to make use of the grader

preview: https://platypus-pr-1407.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/course/ch-labs/lab-1-quantum-circuits

Co-Authored-By: @Tansito 
Co-Authored-By: @frankharkins 

## Implementation details

some of the code cells in Lab 1 have been rewritten to remove the implementation detail and leave it up to the learner to complete. in addition, grader attributes (`grader_import` and `grader_function`) have been added to these specific code cells' metadata field which enable the grader. 

the validation code is defined in `textbook_labs` in the grading service. when grading their code the learner will be made aware whether their solution is correct or not.

## How to read this PR

review the content of the notebook making sure the graded cells explain clearly what needs to be done. 
answer the graded cells and ensure the grader accurately indicates a solution is right or wrong.

## Screenshots

**before**

image

**after**

image

**wrong answer**

image

**correct answer**

image

### CODE REVIEW

**Comment by vabarbosa** [comment]
FYI, @Tansito @frankharkins i opened this to replace #797 (was having issues with the merge conflict)... do we know the status? has the issue (#360) been put on hold for a specific reason (or deprioritized0? just curious since the original PR was in draft for over 4 months.

**Comment by vabarbosa** [comment]
when continuing work on this PR consider using the `grader-id` and `grader-answer` attributes instead as discussed here: https://github.com/Qiskit/platypus/pull/1406
it makes the overall process little bit simpler. you just need to update the grading server (with the validation code) and not necessarily the grading client.

**Comment by Tansito** [comment]
Thanks for this @vabarbosa ! About the status probably @frankharkins will know more about this but the idea was to update the Lab 1 content with the new grader configuration. But we didn't prioritise it yet I think.

**Comment by frankharkins** [comment]
IIRC, after making server PR [#137](https://github.ibm.com/IBM-Q-Software/qac-grading/pull/137) there was something blocking adding the grader to the labs. I guess we never revisited this after it was resolved.

**Comment by vabarbosa** [comment]
cool. thanks. not a problem, i just wanted to make sure there wasn't anything still being waited on.

**Pull request closed without merging**
