### PR TITLE
New language proposal: brazilian portuguese

### PR DESCRIPTION
**Pull request by gustavomirapalheta**
## Screenshots

I'm proposing to have Qiskit materials translated to Brazilian Portuguese language.

### CODE REVIEW

**Comment by gustavomirapalheta** [comment]
Hi, 

I'm confirming that I have joined Gitlocalize.

Regards,

Gustavo

**Review by 0sophy1 — APPROVED** [review]
Confirmed successful joining of GitLocalize

**Review by 0sophy1 — COMMENTED** [review]
need to check with current 'Portuguese (United)' translation group

**Review by veenaiyuri — APPROVED** [review]
Looks good to me.

**Pull request merged**
