### PR TITLE
Updated VQE-molecules notebook for latest version

### PR DESCRIPTION
**Pull request by MarcoBarroca**
## Changes
This should fix issue #1187. I've tried to make as few changes as possible to the code. It works with Qiskit's latest release and gets rid of all the deprecated stuff.

## Implementation details
Followed the migration guide here: https://github.com/Qiskit/qiskit-aqua/blob/main/README.md

Considering part of the code was also deprecated I updated it to be more inline with tutorials available at : https://github.com/Qiskit/qiskit-tutorials/tree/master/tutorials/algorithms

It now uses the new qiskit-nature API and new methods like the ElectronicStructureProblem and its property framework.

### CODE REVIEW

**Comment by Tansito** [comment]
Added @frankharkins to help with the review 🙏

**Review by frankharkins — APPROVED** [review]
Thank you so much! This was a big task that needed doing a long time ago.

I've added this notebook to the pylint checks, most errors were trivial so I addressed them immediately. Still need to write function docstrings, but that is a separate issue.

**Review by frankharkins — APPROVED** [review]

**Comment by MarcoBarroca** [comment]
I just saw a small typo in the noisy simulation section when defining the H2 molecule. I'll open another PR to fix it. Sorry for not catching it before the merge.

**Comment by MarcoBarroca** [comment]
Really sorry about this. PR #1225 shoould fix it.

**Pull request merged**
