### PR TITLE
syllabus review feedback

### PR DESCRIPTION
**Pull request by vabarbosa**
## Changes

updates based on some review feedback
- https://github.com/Qiskit/platypus/pull/855#discussion_r852199630
- https://github.com/Qiskit/platypus/pull/855#discussion_r853736675

**Chapters** title is now hidden when it contains no content.

form is no longer submitted with empty required fields. users are provided with a validity message.

## How to read this PR

- review updates to syllabus form and view files
- create/edit syllabus with & without **Name** and/or **Instructor**

## Screenshots

image

### CODE REVIEW

**Review by Tansito — COMMENTED** [review]
The only thing that I would fix is that for the first time that you fill the inputs all the inputs are validated and you are just starting filling the form. I will prepare a PR trying to improve this UX.

Screenshot 2022-04-22 at 12 12 43

**Comment by Tansito** [comment]
Pristine implementation in #929

**Review by techtolentino — APPROVED** [review]
This looks great @vabarbosa -- thank you for this, as it improves the UX and validation overall.

Only thing I think is that we _should_ (as pointed out by @pandasa123), include asterisks to indicate required fields, especially since we disable the submit button. Scenario: imagine a user can get to the bottom of the page and wonder why they can't move forward with the submission.

Can we add the `*` to the label, and this is good to go 👏 

Screen Shot 2022-04-22 at 7 42 10 AM

**Comment by vabarbosa** [comment]
> This looks great @vabarbosa -- thank you for this, as it improves the UX and validation overall.
> 
> Only thing I think is that we _should_ (as pointed out by @pandasa123), include asterisks to indicate required fields, especially since we disable the submit button. Scenario: imagine a user can get to the bottom of the page and wonder why they can't move forward with the submission.
> 
> Can we add the `*` to the label, and this is good to go 👏
> 

@techtolentino good catch done!

**Review by Tansito — CHANGES_REQUESTED** [review]

**Review by Tansito — APPROVED** [review]
Thanks for this change @vabarbosa 💯

**Review by techtolentino — APPROVED** [review]
Great work @vabarbosa (and @Tansito)

🚀

**Pull request merged**
