### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by NG-Glen**

### CODE REVIEW

**Comment by 0sophy1** [comment]
@NG-Glen  Hi, thank you for joining the Qiskit textbook translation group. Please join https://gitlocalize.com with your GitHub id and leave a message here. Thank you!

**Review by 0sophy1 — DISMISSED** [review]
Gitlocalize onboarded and conflict resolved.

Thank you @NG-Glen ! Enjoy translation!

**Comment by Tansito** [comment]
@0sophy1 could you take a look to the conflict? Thanks 🙏

**Review by 0sophy1 — APPROVED** [review]
conflict resolved.

**Review by Tansito — APPROVED** [review]
Thanks @0sophy1 @NG-Glen 🙏 !

**Pull request merged**
