### PR TITLE
Add script to automaticallly run notebooks

### LINKED ISSUE #355: Rerun textbook regularly
The coloring and sizing of the circuits throughout the textbook have been updated, but the update is only shown when each page of the textbook code is run by a user, or an updated version of each page is pushed to the textbook. 

Is it possible to update all pages of the textbook at once to show the new visuals, either via automation or manually running the textbook locally.

FYI @vabarbosa and @frankharkins

### PR DESCRIPTION
**Pull request by frankharkins**
## Changes

- Added a script `nb_autorun.py` that runs notebooks and reports any errors or warnings it encounters. It can also optionally update the cell outputs, and create GitHub issues.
- Updated notebooks and dependencies to remove or silence problems found by this script. Most of these changes were trivial, with the exception of the quantum volume notebook that needed more attention.
- Updated the code cell outputs.
- Added a GitHub workflow to run this script on PRs with changed notebooks.

## Implementation details

- I've moved some duplicated code across the different tests to it's own file (`tools.py`).
- The script will not execute any cells with the `uses-hardware` tag.
- The script will ignore any warnings in cells with the `ignore-warning` tag.

## How to read this PR

- The main logic in this PR is in the `scripts/content_checks` directory, especially the `nb_autorun.py` script. You can test this script locally using
  ```
  python3 scripts/content_checks/nb_autorun.py
  ```
  > Note: This will take a while to run as most of the notebooks are computationally expensive, so you may want to create test notebooks with errors / warnings in them and either update 
  > ```
  > scripts/content_checks/notebook_paths.txt
  > ```
  > or pass specific paths with 
  > ```
  > python3 scripts/content_checks/nb_autorun.py path/to/file.ipynb
  > ```
- Check out `.github/workflows/test.yml`.
- Optionally, also review the changes made to the notebooks.

## Screenshots

Screenshot 2022-09-01 at 15 59 49

## Additional details

- Closes #355
- This PR supersedes #1505

### CODE REVIEW

**Review by vabarbosa — APPROVED** [review]
@frankharkins thank you! this is awesome. i have approved and you can merge if you are all set. i do have a a couple non-blocking comments:

1. the [pre-reqs](https://github.com/Qiskit/platypus#pre-requisites) should be updated to indicate Python 3.8+ (instead of 3.6)... installing the requirements was failing for me until i updated to 3.8
2. should translated notebooks (e.g., `translations/ja/`, etc.) be checked or not?

**Comment by frankharkins** [comment]
@vabarbosa thanks for the review! I've updated the README.

Ideally we should check the translations too, but someone will need to go through and update them to make sure they run without errors. I can probably make some changes safely (e.g. `ignis` -> `utils`) so I'll try that now, but I'll need a native speaker to update notebooks that need text changes (e.g. the quantum volume notebook).

**Comment by vabarbosa** [comment]
> @vabarbosa thanks for the review! I've updated the README.
> 
> Ideally we should check the translations too, but someone will need to go through and update them to make sure they run without errors. I can probably make some changes safely (e.g. `ignis` -> `utils`) so I'll try that now, but I'll need a native speaker to update notebooks that need text changes (e.g. the quantum volume notebook).
> 
> EDIT: I had a go but the notebooks have diverged too much :/

yeah, i think the translations will be pretty far behind (hence request for a versioning requirement). i think for now we can forgo checking the translations. thanks!

**Review by vabarbosa — APPROVED** [review]
thanks. feel free to merge when you are ready!

**Review by techtolentino — APPROVED** [review]
Tried my best to read through PR, along w/ the back and forth conversation.

LGTM

**Comment by frankharkins** [comment]
Thanks @techtolentino !

**Pull request merged**
