### PR TITLE
Add segment info to Create a Syllabus CTA

### PR DESCRIPTION
**Pull request by techtolentino**
## Changes
Looking into #1010 

## Implementation details

- update `Create a Syllabus` CTA w/ segment info

### CODE REVIEW

**Comment by pandasa123** [comment]
Absolutely amazing!

**Comment by techtolentino** [comment]
@pandasa123 - knowing what we know, now, based on [these findings](https://github.com/Qiskit/platypus/issues/1010#issuecomment-1150196381)

Do you still want us to instrument the `Create a Syllabus` CTA? or is the page load tracking enough?

**Comment by pandasa123** [comment]
Hey @techtolentino, yep I think that it'll be important to understand the user flow through our platform

**Review by korgan00 — APPROVED** [review]
LGTM

**Pull request merged**
