### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by dikshasharma0795**

### CODE REVIEW

**Comment by dikshasharma0795** [comment]
Successfully joined GitLocalizer.

**Review by 0sophy1 — APPROVED** [review]
Conflict resolved and ready to merge!
Thank you @dikshasharma0795, enjoy translation!

**Review by Tansito — APPROVED** [review]
Thanks @dikshasharma0795 @0sophy1 !

**Comment by dikshasharma0795** [comment]
Thank you @0sophy1 & @Tansito  :)

**Pull request merged**
