### PR TITLE
UTokyo lecture problem sets: 03 and 04

### PR DESCRIPTION
**Pull request by kifumi**
## Changes
This is problem sets for the University of Tokyo, the lecture "Introduction to Near-Term Quantum Computing".

- Updated files, 01 and 02.
- Added new files, 03 and 04.
- Updated `notebooks/toc.yaml`.

@veenaiyuri Can you please review this?

### CODE REVIEW

**Review by veenaiyuri — APPROVED** [review]
Thanks, @kifumi . This looks good.

**Comment by veenaiyuri** [comment]
@frankharkins Seems like CLA Assistant fails to handle updating the status. Do you know how this can be fixed?

**Review by frankharkins — APPROVED** [review]

**Comment by frankharkins** [comment]
I'm not sure, but since it's just Kifumi's commits I'll bypass and merge

**Comment by veenaiyuri** [comment]
Thanks @frankharkins !

**Pull request merged**
