### PR TITLE
Updated as per #830

### LINKED ISSUE #830: Textbook content: sec. 6.2 S-gates confusing sentence
Section 6.2 of the (old and new) textbook contains the following sentence:

> It is important to note that unlike every gate introduced in this chapter so far, the S-gate is not its own inverse!

Since the R_phi gate is introduced before, which is generally not its own inverse (obvious from the fact that S is a special case of it) this sentence might be better reformulated, maybe by explicitly naming

> It is important to note that unlike **the Pauli and Hadamard gates** introduced in this chapter so far, the S-gate is not its own inverse!

### PR DESCRIPTION
**Pull request by soumya-s3**
## Changes
Resolves #830 

## Implementation details
Among the gates introduced earlier the Pauli and Hadamard gates are their own inverse but the R_phi gate is not. So I have replaced the term "every gate" by "Pauli and Hadamard gates" to clearly mention that only those two are their own inverse.

## How to read this PR
Review updates to section 6.2 in the chapter [Single Qubit Gates](https://qiskit.org/textbook/ch-states/single-qubit-gates.html)

## Screenshots
Before:
github before

After:
github screenshot

### CODE REVIEW

**Comment by Tansito** [comment]
Thanks for the contribution @soumya-s3 , as part of the process we need that you accept the CLA 🙏

**Comment by soumya-s3** [comment]
> Thanks for the contribution @soumya-s3 , as part of the process we need that you accept the CLA 🙏

Thanks @Tansito  for letting me know. I have signed it.

**Comment by Tansito** [comment]
Thanks @soumya-s3 , I added @frankharkins to the reviewers to take a look when he can. Thanks!

**Review by frankharkins — CHANGES_REQUESTED** [review]
Thanks! [03acba8](https://github.com/Qiskit/platypus/pull/845/commits/03acba834314679b03795cccedacbf4d72343972) looks good, but I think you've included [c57638b](https://github.com/Qiskit/platypus/pull/845/commits/c57638bedb25953237efbfbe4bfd17d570712b63) and [a7dc6fe](https://github.com/Qiskit/platypus/pull/845/commits/a7dc6fe23827b1c2f2d8b313dff3fe8f87160554) by accident?

If those commits fix another issue can you please link them here?

**Comment by frankharkins** [comment]
No worries! You've made a PR from your `main` branch, so any changes you push to that branch will be included. Unfortunately it doesn't look like https://github.com/Qiskit/platypus/pull/845/commits/c57638bedb25953237efbfbe4bfd17d570712b63 fixes #710; you can revert it using `git revert c57638b`, then push to your main branch. I'm still looking at #903.

**Comment by frankharkins** [comment]
I think the solution in https://github.com/Qiskit/platypus/pull/845/commits/a7dc6fe23827b1c2f2d8b313dff3fe8f87160554 looks good! The gates in the second-to-last code cell before "Unique correlations: The Hardy paradox" also need updating.

**Comment by frankharkins** [comment]
Closing, see #922

**Pull request closed without merging**
