### PR TITLE
Add Indonesian to the LOCALIZATION_CONTRIBUTOR.

### PR DESCRIPTION
**Pull request by hanifanrn**
Issue link to add the Indonesian language:

https://github.com/Qiskit/platypus/issues/1026

### CODE REVIEW

**Comment by hanifanrn** [comment]
I have joined GitLocalize using the same GitHub ID: Hanifanrn

**Comment by veenaiyuri** [comment]
@hanifanrn Thank you for your interest in translating the Qiskit Textbook in to Indonesian. Can you please sign the CLA first? After that, please join [GitLocalize](https://gitlocalize.com/) with your GitHub ID and let us know in the comments that you successfully joined. Thank you!

**Review by veenaiyuri — APPROVED** [review]
Reviewed the changes. The user signed the CLA and successfully joined GitLocalize.

**Comment by hanifanrn** [comment]
> @hanifanrn Thank you for your interest in translating the Qiskit Textbook in to Indonesian. Can you please sign the CLA first? After that, please join [GitLocalize](https://gitlocalize.com/) with your GitHub ID and let us know in the comments that you successfully joined. Thank you!

Sure, I've signed the CLA and joined the GitLocalize with the same GitHub ID, ID: Hanifanrn.
Can wait to contribute! :)

**Comment by veenaiyuri** [comment]
@hanifanrn Thank you for joining the project. I just sent you an invite to our GitLocalize project. Please look out for a notice i your inbox from GitLocalize.

**Comment by hanifanrn** [comment]
> @hanifanrn Thank you for joining the project. I just sent you an invite to our GitLocalize project. Please look out for a notice i your inbox from GitLocalize.

You're welcome, I've checked my GitLocalize and found the project. I really appreciate your fast response, thanks a lot!

**Pull request merged**
