### PR TITLE
Introduction Practice Exam

### LINKED ISSUE #667: As a Professor, I want to integrate Problem Sets into my Syllabus, so I can test students after they learn concepts
## Background

Homeworks, Practice Exams, and Projects are important ways to test student comprehension. With the [Assessment Experience](https://github.com/Qiskit/platypus/issues/1079) and [Problem Set Bank](https://github.com/Qiskit/platypus/issues/1259), professors should be able to add Problem Sets into their Syllabus

Related:

- [Problem Sets Bank](https://github.com/Qiskit/platypus/issues/1259)
- [Problem Set Bank collection](https://github.com/Qiskit/platypus/issues/1260)
- [Integrations into Syllabus](https://github.com/Qiskit/platypus/issues/667)

## MVP Goal

> Professor should be able to select canned Problem Sets on a Syllabus

## Acceptance Criteria

- [ ] Syllabus dropdown to switch between Chapters, Tutorials, and Problem Sets
- [ ] Professor should be able to add Problem Set to a section with a checkbox

### PR DESCRIPTION
**Pull request by pandasa123**
## Changes

- Added a single page to `toc.yaml`
- Added exam assets in `notebooks/exams/` for now

## Implementation details

This leverages MCQ + Auto-Grader code interactions. The actual auto-grader code hasn't been implemented yet

## How to read this PR

~~Temporarily, `/course/exams/intro-practice-exam` [here](https://platypus-pr-809.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/course/exams/intro-practice-exam). Ideally, I'd love to move this above to `/exams/intro-practice-exam` instead but I'd imagine that requires changes to the sitemap~~

preview link from [`/exams/intro-practice-exam`](https://platypus-pr-809.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/exams/intro-practice-exam) endpoint

## Screenshots

This is the very very basic MVP that resolves #667.

### CODE REVIEW

**Comment by JRussellHuffman** [comment]
I just noticed that when the user clicks "Run" or "Grade" the loading state is the same. It says "Running". Is it possible to have it say "Grading" when "Grade" is clicked? I thought I clicked the wrong button at first.

**Comment by vabarbosa** [comment]
fyi, @pandasa123 regarding your comment in the description:

> _Temporarily, `/course/exams/intro-practice-exam` [here](https://platypus-pr-809.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/course/exams/intro-practice-exam). Ideally, I'd love to move this above to `/exams/intro-practice-exam` instead but I'd imagine that requires changes to the sitemap_

the previous commit (https://github.com/Qiskit/platypus/pull/809/commits/2fb44cef2873fa7b793912e337dd5869c48b0789) enables the [`/exams/<exam_id>`](https://platypus-pr-809.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/exams/intro-practice-exam) endpoint.

**Comment by pandasa123** [comment]
Hey @vabarbosa, yep it definitely makes sense to add `/problem-sets/`

**Comment by vabarbosa** [comment]
> I just noticed that when the user clicks "Run" or "Grade" the loading state is the same. It says "Running". Is it possible to have it say "Grading" when "Grade" is clicked? I thought I clicked the wrong button at first.

@JRussellHuffman checkout https://github.com/Qiskit/platypus/pull/1425

**Comment by JRussellHuffman** [comment]
will do. thanks

**Pull request closed without merging**
