### PR TITLE
Add ES_UN to LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by clausia**
## Changes

Add myself as part of the team to translate the Textbook into Spanish.

Related: https://github.com/Qiskit/platypus/issues/1014

### CODE REVIEW

**Review by veenaiyuri — DISMISSED** [review]
The user signed the CLA and has also joined GitLocalize successfully.

**Review by techtolentino — CHANGES_REQUESTED** [review]
@clausia -- thanks for this.

Please resolve the conflict then commit... (basically, this will happen whenever two or more contributors will be touching the same file).

Reach out if you need any clarification.

Thanks again! 👏

**Comment by clausia** [comment]
> @clausia -- thanks for this.
> 
> Please resolve the conflict then commit... (basically, this will happen whenever two or more contributors will be touching the same file).
> 
> Reach out if you need any clarification.
> 
> Thanks again! 👏

Thanks, the conflict has been resolved.

**Review by techtolentino — APPROVED** [review]
LGTM 👏 

Thanks @clausia

**Pull request merged**
