### PR TITLE
Fix amplitude direction

### PR DESCRIPTION
**Pull request by frankharkins**
## Changes

Fix ampltidue direction (see https://github.com/qiskit-community/qiskit-textbook/issues/1481 for details).

### CODE REVIEW

**Review by husayngokal — APPROVED** [review]
Perfect 👍

**Review by vabarbosa — APPROVED** [review]
thank you!

**Comment by husayngokal** [comment]
Thanks! Just wanted to ask though, how often do the website files get replaced with the main branch? I'm not that familiar with Git workflows 😅

**Comment by vabarbosa** [comment]
> Thanks! Just wanted to ask though, how often do the website files get replaced with the main branch? I'm not that familiar with Git workflows 😅

hi, we have it set up to update nightly. however, there is a current issue with the build script (we are investigating) so it has not updated last 2 days

**Comment by husayngokal** [comment]
Got it 👍

**Pull request merged**
