### PR TITLE
Minor bug fixes in Algorithm Design course

### PR DESCRIPTION
**Pull request by pandasa123**
## Implementation details

- Observable name
- Setting `x0` for `COBYLA`

### CODE REVIEW

**Review by vabarbosa — APPROVED** [review]
thank you!

**Review by frankharkins — COMMENTED** [review]
I get an error in the last cell of "applications"...

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[33], line 5
      1 from qiskit.quantum_info import Statevector
      3 optimal_circuit = result.optimal_circuit.bind_parameters(result.optimal_parameters)
----> 5 x = max_cut.sample_most_likely(Statevector(optimal_circuit))
      6 print("energy:", result.eigenvalue.real)
      7 print("time:", result.optimizer_time)

File ~/Documents/platypus/.venv/lib/python3.8/site-packages/qiskit_optimization/applications/optimization_application.py:81, in OptimizationApplication.sample_most_likely(state_vector)
     79     return x
     80 else:
---> 81     n = int(np.log2(state_vector.shape[0]))
     82     k = np.argmax(np.abs(state_vector))
     83     x = np.zeros(n)

AttributeError: 'Statevector' object has no attribute 'shape'
```

The cost function page runs fine.

**Comment by frankharkins** [comment]
@pandasa123 I was a few minutes too late with the review, can you make a follow-up PR to fix this?

**Comment by vabarbosa** [comment]
> @pandasa123 I was a few minutes too late with the review, can you make a follow-up PR to fix this?

sorry about that! my fault.

**Comment by pandasa123** [comment]
I actually couldn't replicate this issue locally or in Lab oddly enough

**Pull request merged**
