### PR TITLE
translations preview

### PR DESCRIPTION
**Pull request by vabarbosa**
this PR includes translated content for publishing.

the PR includes a preview link (once build/test is complete) to preview the translations (and confirm no build issues) before they are published. for example, you can preview out the `Introduction` course for various languages:

- `English`: https://platypus-pr-1609.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/course/introduction/why-quantum-computing
- `Japanese`: https://platypus-pr-1609.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/course/introduction/why-quantum-computing?hl=ja
- `Spanish`: https://platypus-pr-1609.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/course/introduction/why-quantum-computing?hl=es
- `Korean`: https://platypus-pr-1609.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/course/introduction/why-quantum-computing?hl=ko
- `Portuguese`: https://platypus-pr-1609.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/course/introduction/why-quantum-computing?hl=pt

related: https://github.com/Qiskit/platypus/pull/1603

### CODE REVIEW

**Comment by vabarbosa** [comment]
@Qiskit/qiskit-translation i created the branch (`feat/translations`) and this PR.

we can start previewing the translation effort in a live deployment. just submit updates to this branch instead of `main`.
commits/merges to this PR branch will trigger deployment with updated content. for example, you can check out the `Introduction` course for various languages:

- `English`: https://platypus-pr-1609.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/course/introduction/why-quantum-computing
- `Japanese`: https://platypus-pr-1609.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/course/introduction/why-quantum-computing?hl=ja
- `Spanish`: https://platypus-pr-1609.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/course/introduction/why-quantum-computing?hl=es
- `Korean`: https://platypus-pr-1609.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/course/introduction/why-quantum-computing?hl=ko
- `Portuguese`: https://platypus-pr-1609.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/course/introduction/why-quantum-computing?hl=pt

&nbsp;

with that said, there is a build issue with the Korean `ch-states` course (see [the build logs](https://github.com/Qiskit/platypus/actions/runs/3176153425/jobs/5175112276#step:10:1504)).

there are also content/rendering issues with some of the translated notebooks (navigate through some of the translated pages and compare with English version). 

for example, looking at `Introduction` course sidebar:

**English**

image

**Spanish**

image

**Korean**

image

&nbsp;

a couple things to look out for is the headings in the notebooks and the latex/formulas. hopefully, these should not need to be changed during translation as they impact the sidebar and rendering.

let me know if you have any questions or need assistance troubleshooting some of these!

---

CC @ilyaspiridonov @kifumi @clausia

**Comment by clausia** [comment]
@vabarbosa 
It's awesome that we can get a preview of the translations! Thank you for this :)

I have some questions regarding the use of this branch (`feat/translations`), I hope this is a good place to ask them (if not please ignore them):

- What about the toc.yaml file that appears in GitLocalize? Will it just be ignored from now on? Because adding translated sections will be by creating a PR (to this branch first), is this correct?
- So when we send a PR from GitLocalize it will be to this branch (`feat/translations`), right? Will it be automatic, or should we change the destination branch by hand once the PR is created using GitLocalize? Will we have permission to do this? (the moderators and/or the admins on GitLocalize)
- The text "Reading time: ~xx min" that appears at the top of the pages seems to me that it is in the file "server/templates/textbook.pug", but in the case of Spanish, for example, it is already translated, but there is no such file under "translations/es", nor I see it in this branch (`feat/translations`), where can we update it?, the current translation is not quite right 😅 
  
- Is it possible that the reason that the menu on the left for the Spanish case is due to the fact that only the first notebook is included in the toc.yaml? I mention it, because since there are no other files in `url: /introduction` (inside the toc.yaml file), then there is no reason for any header to have LaTeX errors and that is causing bad rendering (the only notebook included in the toc file for Spanish it is `/intro/why-quantum-computing` and that does not have headers with LaTeX, in fact those headers look good in the menu on the left)
  

Thanks in advance!

---
CC @ilyaspiridonov @kifumi

**Comment by ilyaspiridonov** [comment]
Some thoughts and PR: 
1) Created a pilot PR to this branch with some LaTex fixes: [#1610](https://github.com/Qiskit/platypus/pull/1610) - is my understanding correct that we should send any fixes to this branch as PRs? 
2) GitLocalize sits on top of the `main` branch, so all translation pull requests with the actual translated notebooks will be sent to the `main` branch, not `feat/translations`
3) Those could potentially be merged into `main` as done previously, and `feat/translations` could be used only when adding translated articles in localized `toc.yaml` (as only in this case the translated articles will be included in the build - hence the need to preview at this point only) 
4) LaTex being broken by GitLocalize is a know issue (as GitLocalize just can't parse those). It's now included in the dev pipeline as high priority (next task after the current 'Translate Metadata' task).

**Comment by vabarbosa** [comment]
this `feat/translations` branch/PR is to help with preview of translated content as we prepare to publish them.

ideally, the only changes in this PR would be the `config.yaml` (i.e. languages to publish) and the language specific`toc.yaml` (adding the localized notebooks). everything else (e.g., updates to the notebooks or new translated notebooks, etc) would go into `main'. 

regarding to some of the comment

>_Is it possible that the reason that the menu on the left for the Spanish case is due to the fact that only the first notebook is included in the toc.yaml?_

yes, you are correct.

> _So when we send a PR from GitLocalize it will be to this branch (feat/translations), right?_

you should continue to work based off of the `main` branch as you are working now (no need to change your current workflow). we can rebase/update this branch as needed off of `main` to get preview of latest content.

>_The text "Reading time: ~xx min" that appears at the top of the pages seems to me that it is in the file "server/templates/textbook.pug", but in the case of Spanish, for example, it is already translated, but there is no such file under "translations/es", nor I see it in this branch (feat/translations), where can we update it?, the current translation is not quite right 😅_

it should be in the `strings.yaml` in each language (e.g., `translations/ja/strings.yaml`). the `strings.yaml` contains all other strings available on the page but that are not part of the actual notebook content. we will need to investigate where the translations is coming from in this specific case.

> _Created a pilot PR to this branch with some LaTex fixes: https://github.com/Qiskit/platypus/pull/1610 - is my understanding correct that we should send any fixes to this branch as PRs?_

yeah, any fixes to this branch should come in as PRs. however, it would be better submitting against `main` so that way the notebooks dont get out of sync with what is in main (and also avoid merge conflicts) when pulling updates from `main` into this branch.

thank you @clausia @ilyaspiridonov

**Comment by vabarbosa** [comment]
@clausia the Spanish translation of `Reading time` was defaulting to the translation that was provided by the platform we use. i have added a `strings.yaml` for Spanish and added a translation of `Reading time` i got using [Watson Language Translator](https://www.ibm.com/demos/live/watson-language-translator/self-service/home). feel free to update as needed 😄 

fyi, i also added the `strings.yaml` for Portuguese and Korean. all new languages added should include a `strings.yaml` that must also get translated.

**Comment by clausia** [comment]
> @clausia the Spanish translation of `Reading time` was defaulting to the translation that was provided by the platform we use. i have added a `strings.yaml` for Spanish and added a translation of `Reading time` i got using [Watson Language Translator](https://www.ibm.com/demos/live/watson-language-translator/self-service/home). feel free to update as needed 😄

Thanks a lot, translation is perfect 😃

**Comment by ilyaspiridonov** [comment]
> 
@vabarbosa While this branch/PR idea sounds really great (thanks for implementing this!), would it make sense to add a GitHub action later on to run a test build (using Netlify or similar) on all incoming PRs to `master`  (e.g. whenever a toc.yaml is updated for any language)?
I was thinking kind of what folks at Google are using (see Deploy preview): [https://github.com/GoogleChrome/developer.chrome.com/pull/3903](https://github.com/GoogleChrome/developer.chrome.com/pull/3903)
Not an expert though, so not sure if this would be a good fit :)

**Comment by vabarbosa** [comment]
@ilyaspiridonov thanks... yeah, we actually have similar a GitHub Action setup for PRs created in this repo. we just have it disabled for the time being for translation PRs, but we will be visiting that again soon & see if we are ready to re-enable it (maybe right after the translation team reviews and we merge this PR)

**Pull request closed without merging**
