### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by Fahlevi20**

### CODE REVIEW

**Comment by Fahlevi20** [comment]
Successfully

**Comment by Fahlevi20** [comment]
> [CLA assistant check](https://cla-assistant.io/Qiskit/platypus?pullRequest=1404) All committers have signed the CLA.

**Review by Tansito — APPROVED** [review]

**Review by 0sophy1 — APPROVED** [review]
Thank you @Fahlevi20  for showing your support to translate the textbook! I have confirmed that you signed the CLA and that you have successfully joined GitLocalize. This PR is ready to merge.

**Comment by Fahlevi20** [comment]
> 

Thank you very much

**Pull request merged**
