### PR TITLE
Fixed typo in description

### PR DESCRIPTION
**Pull request by daiki0623**
## Changes

Fixed typo "In practise" to "In practice".

### CODE REVIEW

**Comment by Tansito** [comment]
Thanks for this PR @daiki0623 . From what I could see you are adding style changes to the PR that they are not needed. Could you clean those changes and only upload the text change? Thank you!

**Review by Tansito — CHANGES_REQUESTED** [review]
Thanks for this PR @daiki0623 . From what I could see you are adding style changes to the PR that they are not needed. Could you clean those changes and only upload the text change? Thank you!

**Comment by daiki0623** [comment]
> Thanks for this PR @daiki0623 . From what I could see you are adding style changes to the PR that they are not needed. Could you clean those changes and only upload the text change? Thank you!

Thank you for pointing out, removed unnecessary modifying.

**Review by frankharkins — APPROVED** [review]
Thank you!

**Review by Tansito — APPROVED** [review]
Thank you @daiki0623 for the fix!  And thank you @frankharkins and @techtolentino too 🙏

**Pull request merged**
