### PR TITLE
Remove user whose name was added to different language

### PR DESCRIPTION
**Pull request by ni784**
removed Czech languages / @ni784 at the Bengali contributor list

### CODE REVIEW

**Comment by SooluThomas** [comment]
Hi @ni784, We haven't opened Czech yet in GitLocalize. To add a new language other the ones already listed in the LOCALIZATION_CONTRIBUTORS file, please [follow these instructions](https://github.com/Qiskit/platypus/blob/main/TRANSLATING.md#how-to-add-a-new-language). Feel free to ask questions here or in the issue (when you open one).

Thanks for your interest in contributing!

**Comment by Tansito** [comment]
Correct me if I'm wrong @SooluThomas but the PR is fixing an error in the format. Can you confirm us to be able to merge or reject this PR?

cc: to @0sophy1 here too

**Comment by 0sophy1** [comment]
> Correct me if I'm wrong @SooluThomas but the PR is fixing an error in the format. Can you confirm us to be able to merge or reject this PR?
> 
> cc: to @0sophy1 here too

Hi @Tansito We've approved the previous PR because @ni784 was added to already added languages while marking the name part as Czech and there is no way that I can identify Czech is not a "name of @ni784 ". 
But as @ni784 wanted to start a new language, we would like to ask you to follow the standard process for adding a new language.  So I would like to close this PR and remove @ni784 from our contributor list.

**Review by 0sophy1 — APPROVED** [review]
Thank you so much @ni784 for your interest in localization To start the Czech localization team, please contact Soolu or Yuri by following our standard process after gathering 3 more Czech translators. Thank you for your cooperation!

**Comment by 0sophy1** [comment]
Sophy edited PR - removed Czech languages / @ni784  at the Bengali contributor list

**Comment by ni784** [comment]
Oh well... Have to wait until ... forever I guess :-) Take care, everyone!

**Comment by SooluThomas** [comment]
@ni784  To add a new language other the ones already listed in the LOCALIZATION_CONTRIBUTORS file, please [follow these instructions](https://github.com/Qiskit/platypus/blob/main/TRANSLATING.md#how-to-add-a-new-language). Feel free to ask questions here or in the issue (when you open one).

Please note that you'll need a minimum of 3 people to start a language.

**Pull request closed without merging**
