### PR TITLE
add Japanese translation files

### PR DESCRIPTION
**Pull request by kifumi**
## Changes
We have [Japanese version of old Qiskit textbook](https://qiskit.org/textbook/ja/preface.html), so we can use it for the localization project of new Qiskit textbook.  I copied the Japanese translated notebook files to this repo.

### CODE REVIEW

**Review by veenaiyuri — DISMISSED** [review]
Yes, these files are necessary to jump-start Japanese translations. I approve for mergining these changes.

**Comment by veenaiyuri** [comment]
@vabarbosa Can you review and merge this request?

**Review by techtolentino — COMMENTED** [review]
Thanks for this @kifumi -- this is a great update 👏 

I was able to pull down this branch to my own machine and have a look — it builds fine. I also worked with @frankharkins to discuss this.

One thing we'll need too, is the table of contents need to be updated. 

https://github.com/kifumi/platypus/blob/ja-translation/translations/ja/toc.yaml

This will let the UI know which pages have a translated version.

We're here if you need any help or clarification with this. Thanks again!

**Comment by techtolentino** [comment]
@kifumi -- just wanted to update on this PR.

I was working with @frankharkins on the review, it turns out that there were a few build issues and it prevented a number of chapters from rendering properly.

Thank you for your patience as we continue to review. 

@frankharkins was actually in the process resolving some of the syntax issues he noticed. Once the project builds fully and the TOC.yaml is working properly, we can approve and merge.

**Comment by kifumi** [comment]
@techtolentino @frankharkins Thank you so much.  I merged the PR which Frank made for my repo.

**Review by frankharkins — APPROVED** [review]
Appears everything's working now so LGTM! Thanks again

**Review by techtolentino — APPROVED** [review]
Awesome collaboration @kifumi @frankharkins 
(once the checks pass, we'll get this merged)

👏 🙏

**Pull request merged**
