### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by lucifer1112k**
- added my name as the localization contributor for the Bengali language.

### CODE REVIEW

**Review by vabarbosa — APPROVED** [review]
thanks

**Comment by veenaiyuri** [comment]
@lucifer1112k Thanks for joining the Qiskit Textbook localization project. Please let us know in the comments when you successfully joined GitLocalized so I can add you to the project.

**Comment by lucifer1112k** [comment]
@veenaiyuri i've joined GitLocalize using my github. waiting for the merge.

**Review by veenaiyuri — APPROVED** [review]
The user has signed the CLA and successfully joined GitLocalize.

**Comment by veenaiyuri** [comment]
@lucifer1112k  I confirmed that you joined GitLocalize and added you to our test project. Please check your inbox for an email titled '[GitLocalize] You have been assigned a new role.' to get started with translating in the test repo. Our official repo will be opened next week and we will notify you separately with details! Thanks!

**Comment by lucifer1112k** [comment]
Thank you so much @veenaiyuri I will look forward to the next email.

**Pull request merged**
