### PR TITLE
enable textbook versioning

### PR DESCRIPTION
**Pull request by vabarbosa**
this PR is part of a bigger set of changes required as the Textbook gets re-organized/versioned: https://github.com/Qiskit/platypus/issues/2046

## Changes

Fixes https://github.com/Qiskit/platypus/issues/1844

this PR adds the support and includes current version and legacy version of textbook

## Implementation details

- textbook content moved to a separate repo
- update URL to handle versioning
- add versioning banner
- support versioning translation workflow
- remove references to **_beta_**

## Related

https://github.com/Qiskit/qiskit.org/pull/3105

### CODE REVIEW

**Comment by JRussellHuffman** [comment]
Is there a preview URL for this that I can peak at?

**Comment by vabarbosa** [comment]
> Is there a preview URL for this that I can peak at?

there are some merge conflicts we need to resolve before preview link

**Comment by vabarbosa** [comment]
@frankharkins thank you! i created this PR so i can't mark it approved but when you are ready i can merge it

**Review by frankharkins — APPROVED** [review]
Let's do it

**Pull request merged**
