### PR TITLE
merge feat/user account v1

### PR DESCRIPTION
**Pull request by vabarbosa**
Fixes https://github.com/Qiskit/platypus/issues/850 (keeping as draft until we get go ahead to merge) 

Preview: https://platypus-pr-885.ecy0akwlcpw.us-south.codeengine.appdomain.cloud/account

## Changes

Completes User Account v1 milestone

## Implementation details

the top navbar/header is updated to include an additional item (profile link) to allow easier access to account page
 
## Screenshots

**small screen**
image

**large screen**
image

### CODE REVIEW

**Comment by Tansito** [comment]
We will need to take a look to #799 that I think is not finished (we closed it by error I think).

**Comment by Tansito** [comment]
After some discussion we think we are fine with the current solution and we can improve the logic following the different uses cases described in the issue: #258

**Comment by vabarbosa** [comment]
> Very excited to see this! For the smaller sizes is it possible to get the styling of the profile button a little closer to the [designs](https://www.figma.com/file/SOnOgCGQIWx4oAlSFhIsIX/1972-User-account?node-id=559%3A4517)? The purple and underline will make it feel much better.
> 

@JRussellHuffman the border color has been updated. it should be present/viewable as soon as the preview build finishes

**Comment by JRussellHuffman** [comment]
Looks much better, thank you!

**Review by eddybrando — COMMENTED** [review]
Looks great! _Soft approved_ from my end.

@lerongil & @pandasa123, regarding https://github.com/Qiskit/platypus/issues/261, should we wait or can we already ship this?

**Review by eddybrando — DISMISSED** [review]
After checking with @vabarbosa, @pandasa123 and @lerongil, this is ready for shipping 🙂

**Review by eddybrando — APPROVED** [review]

**Pull request merged**
