### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by jaeunkim**
## Changes
Adding Jaeun Kim to the Korean translation team.

### CODE REVIEW

**Comment by jaeunkim** [comment]
Hi! I have successfully joined GitLocalize.

**Review by veenaiyuri — DISMISSED** [review]
The user has signed the CLA and successfully joined GitLocalize.

**Comment by veenaiyuri** [comment]
@jaeunkim Thanks for showing your support to translate the textbook into Korean! I have confirmed that you signed the CLA and that you have successfully joined GitLocalize. You will receive notification from GitLocalize with a link to the platypus project soon. 
@techtolentino can you please approve and merge this PR when you have time? Thanks!

**Review by 0sophy1 — APPROVED** [review]
Ready to me merged!

**Pull request merged**
